name: Corehub CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.17.0', '20.x']

    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: npm i

      # Run linter
      - name: Run Linter
        run: npm run lint

      # Check Prettier
      - name: Check Prettier
        run: npm run format

      # Run tests
      - name: Run Tests
        run: npm run test

      # Run build
      - name: Build
        run: npm run build
